### PR TITLE
Add ability to fetch README and CHANGELOG from URLs specified in podspec (#1) (#2)

### PR DESCRIPTION
**Pull request by jrullman**
With this change, podspecs can contain top-level keys 'readme' and 'changelog' with URLs to fetch the README and CHANGELOG from.

### CODE REVIEW

**Comment by orta** [comment]
Cool, I've fixed up some syntax errors and added CI to verify in case anyone else sends a PR

**Comment by orta** [comment]
This isn't documented, so it could probably do with letting people know somehow but that's not a blocker for now

**Comment by orta** [comment]
I believe this is deployed too

**Comment by jrullman** [comment]
How long does it take for the webhook to run? The ARCore pod was updated about 24 hours ago, but the pod page content (readme, changelog) is still not updated yet (https://cocoapods.org/pods/ARCore#changelog). The new README and CHANGELOG files are accessible and parse correctly as Markdown. Do I just have to wait longer?

**Comment by jrullman** [comment]
It has now been 2 full days since we pushed our new pod version, and the pod page is still not updated. Did the metadata service fail or something?

**Pull request merged**
